### ISSUE TITLE
Use github for dependencies

### ISSUE THREAD

**Issue by vivainio** [teelahti/gp-janitor#1]
You should probably import these to avoid hg dependency:

https://github.com/btcsuite/winsvc/tree/master/winapi

https://github.com/kardianos/service

**Comment by teelahti** [comment]
Did not think of that as Go itself requires hg. I'll try.

**Comment by teelahti** [comment]
winapi stuff [is moving to official golang.org/x/sys](https://go-review.googlesource.com/#/c/9104/), and Kardianos's service does not compile ATM when taken from Github. I'll keep this ticket open and move once these dependencies have sorted their own migration.

**Comment by teelahti** [comment]
Now merged: https://godoc.org/golang.org/x/sys

I'll change to this package soon.
